curve25519: fmul -> fmul320
Since LIBC 2.28 fmul exists in math.h, without this commit
we will have following errors during build with _GNU_SOURCE
define:

In file included from OS_portable.h:80,
                 from OS_nonportable.c:34:
../includes/curve25519.h:43:9: error: conflicting types for 'fmul'
 bits320 fmul(const bits320 in2,const bits320 in);
         ^~~~